/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package UI;


import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;


/**
 *
 * @author kujo7
 */
public class Register extends javax.swing.JFrame {

      /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fillname = new javax.swing.JTextField();
        jcreate = new javax.swing.JButton();
        fillpass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/for img and icons/Black Modern Cargo Vessel Ship Design Logo Template.png"))); // NOI18N
        lbl.setText("tite");
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -10, 502, 520));
        lbl.getAccessibleContext().setAccessibleName("register");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create an account");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create user name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Create Password");

        fillname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillnameActionPerformed(evt);
            }
        });

        jcreate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cafe Image & Icon/images/save.png"))); // NOI18N
        jcreate.setText("Create Account");
        jcreate.setIconTextGap(3);
        jcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcreateActionPerformed(evt);
            }
        });

        fillpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cafe Image & Icon/images/close.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(jcreate)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fillpass, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fillname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fillpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jcreate)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 500, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fillnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fillnameActionPerformed

    private void jcreateActionPerformed(java.awt.event.ActionEvent evt) {
        String username = fillname.getText();
        String password = new String(fillpass.getPassword());
       
        // Validation
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please fill all fields",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        try (Connection conn = MyConnection.getConnection()) {
            // Check if username exists
            String checkUser = "SELECT * FROM login WHERE username = ?";
            try (PreparedStatement checkStmt = conn.prepareStatement(checkUser)) {
                checkStmt.setString(1, username);
                ResultSet rs = checkStmt.executeQuery();
               
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this,
                        "Username already exists! Choose another one",
                        "Registration Failed!",
                        JOptionPane.ERROR_MESSAGE);
                    return;  // Exit the method if username exists
                }
               
                // If username doesn't exist, proceed with registration
                String sql = "INSERT INTO login (username, password) VALUES (?, ?)";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, username);
                    pstmt.setString(2, password);
                   
                    int rowsAffected = pstmt.executeUpdate();
                   
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(this,
                            "Registration is Successful!",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                        setVisible(false);
                        new LoginScreen().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this,
                            "Registration failed, please try again.",
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                "Database error: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          int a = JOptionPane.showConfirmDialog(null, "Do you want to cancel", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
             new LoginScreen().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fillname;
    private javax.swing.JPasswordField fillpass;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jcreate;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
